apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpcgoonch-nonheadless-client-cronjob
  labels:
    app: grpcgoonch-nonheadless-client
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grpcgoonch-nonheadless-client
    spec:
      template:
        spec:
          containers:
          - name: grpcgoonch-nonheadless-client
            image: thaigoonch/grpcgoonch-nonheadless-client:1.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"